name: ci

on: push

jobs:
  push-stocker:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for drat to Update
        run: sleep 300s
        shell: bash
      - name: Trigger stocker Build
        run: |
          curl -XPOST -u "jakejh:${{secrets.JAKEJH_PAT}}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/hugheylab/stocker/dispatches \
            --data '{"event_type": "build_application"}'
        shell: bash
